name: NoCivilSpawns
main: com.sleaker.NoCivilSpawns.NoCivilSpawns
version: 1.4.6
author: Sleaker
description: >
             A plugin that cancels mob spawn events if they occur
             too close to user created blocks, or certain custom
             set blocks.